### ISSUE TITLE
_inital_mu error during notebook example

### ISSUE THREAD

**Issue by LucaNap** [ucl-exoplanets/TauREx3_public#13] opened 2021-04-10 15:03 UTC
Hello, I get the following error on Windows 10 (Anaconda) after running the notebook in the example folder:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-88-cedb500b1550> in <module>
>      15 tm.add_contribution(RayleighContribution())
>      16 tm.build
> ---> 17 res = tm.model()
>      18 plt.figure()
>      19 
> 
> D:\Anaconda3\lib\site-packages\taurex\model\simplemodel.py in model(self, wngrid, cutoff_grid)
>     388 
>     389         # Setup profiles
> --> 390         self.initialize_profiles()
>     391 
>     392         # Clip grid if necessary
> 
> D:\Anaconda3\lib\site-packages\taurex\model\simplemodel.py in initialize_profiles(self)
>     137         # Initialize the atmosphere with a constant gas profile
>     138         if self._initialized is False:
> --> 139             self._inital_mu.initialize_chemistry(self.pressure.nLayers,
>     140                                                  self.temperatureProfile,
>     141                                                  self.pressureProfile,
> 
> AttributeError: 'TransmissionModel' object has no attribute '_inital_mu'

Also all the "example" .par are not working, perhaps due to recent updates of taurex.

**Comment by ahmed-f-alrefaie** [comment] 2021-04-10 16:22
Thanks for bringing it up. This error usually occurs when build hasn't been called before model.
I'll take a look at it and see what the issue is.

I notice that in your exception stack that tm.build does not have any parenthesis. If you replace it with tm.build() does it work?

**Comment by LucaNap** [comment] 2021-04-10 16:32
> 
> 
> Thanks for bringing it up. This error usually occurs when build hasn't been called before model.
> I'll take a look at it and see what the issue is.
> 
> I notice that in your exception stack that tm.build does not have any parenthesis. If you replace it with tm.build() does it work?

It's returning the same error... thank you for the quick response!

**Comment by ahmed-f-alrefaie** [comment] 2021-04-10 16:55
Which version of numba and numpy are you using and were they installed using pip or conda? There is a related issue: https://github.com/numba/numba/issues/6041 caused by some incompatibility between versions

You can try uninstalling both and using the conda versions:
`pip uninstall numpy numba`
`conda install numpy numba`

**Comment by LucaNap** [comment] 2021-04-10 17:44
They were installed with conda. But I have tried anyway to do what you have suggested and the issue is still there.

**Comment by LucaNap** [comment] 2021-04-10 18:22
@ahmed-f-alrefaie I made it work by forcing conda to install the latest versions of astropy, numpy and numba (for some reason it wouldn't "update" to the newer versions). This is just to say that the issue was with the other packages, not Taurex... but yeah those parentheses are needed in the notebook! Thank you

**Comment by ahmed-f-alrefaie** [comment] 2021-04-10 18:40
Thanks for bringing it up :) I'm glad it worked for you! I'll fix the notebook. Closing the issue

**Closed by ahmed-f-alrefaie** 2021-04-10 18:40 UTC
